CREATE TABLE IF NOT EXISTS sys_user (
    id BIGINT NOT NULL,
    user_no VARCHAR(32) NOT NULL,
    user_type VARCHAR(32) NOT NULL,
    display_name VARCHAR(64) NOT NULL,
    mobile VARCHAR(32),
    avatar_url VARCHAR(255),
    wecom_user_id VARCHAR(64),
    wecom_external_user_id VARCHAR(64),
    wx_openid VARCHAR(64),
    wx_unionid VARCHAR(64),
    supplier_id BIGINT,
    status VARCHAR(32) NOT NULL,
    last_login_at DATETIME(3),
    created_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    created_by BIGINT,
    updated_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    updated_by BIGINT,
    version BIGINT NOT NULL DEFAULT 0,
    deleted_flag TINYINT(1) NOT NULL DEFAULT 0,
    deleted_at DATETIME(3),
    deleted_by BIGINT,
    PRIMARY KEY (id),
    UNIQUE KEY uk_sys_user_no (user_no),
    UNIQUE KEY uk_sys_user_wecom_user_id (wecom_user_id),
    UNIQUE KEY uk_sys_user_wx_openid (wx_openid),
    UNIQUE KEY uk_sys_user_mobile_type (mobile, user_type),
    KEY idx_user_type_status (user_type, status),
    KEY idx_user_supplier_id (supplier_id),
    KEY idx_user_unionid (wx_unionid),
    KEY idx_user_external_user_id (wecom_external_user_id)
);

CREATE TABLE IF NOT EXISTS sys_role (
    id BIGINT NOT NULL,
    role_code VARCHAR(64) NOT NULL,
    role_name VARCHAR(64) NOT NULL,
    role_type VARCHAR(32) NOT NULL,
    data_scope VARCHAR(32) NOT NULL,
    permission_codes JSON,
    status VARCHAR(32) NOT NULL,
    sort_no INT NOT NULL DEFAULT 0,
    description TEXT,
    created_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    created_by BIGINT,
    updated_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    updated_by BIGINT,
    version BIGINT NOT NULL DEFAULT 0,
    deleted_flag TINYINT(1) NOT NULL DEFAULT 0,
    deleted_at DATETIME(3),
    deleted_by BIGINT,
    PRIMARY KEY (id),
    UNIQUE KEY uk_sys_role_code (role_code),
    UNIQUE KEY uk_sys_role_name (role_name),
    KEY idx_role_status_sort (status, sort_no)
);

CREATE TABLE IF NOT EXISTS sys_user_role (
    id BIGINT NOT NULL,
    user_id BIGINT NOT NULL,
    role_id BIGINT NOT NULL,
    grant_status VARCHAR(32) NOT NULL,
    granted_by BIGINT,
    granted_at DATETIME(3),
    revoked_by BIGINT,
    revoked_at DATETIME(3),
    created_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    created_by BIGINT,
    updated_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    updated_by BIGINT,
    version BIGINT NOT NULL DEFAULT 0,
    PRIMARY KEY (id),
    UNIQUE KEY uk_sys_user_role_user_role (user_id, role_id),
    KEY idx_user_role_user (user_id),
    KEY idx_user_role_role (role_id),
    KEY idx_user_role_grant_status (grant_status)
);

CREATE TABLE IF NOT EXISTS crm_lead (
    id BIGINT NOT NULL,
    lead_no VARCHAR(32) NOT NULL,
    name VARCHAR(64) NOT NULL,
    mobile VARCHAR(32) NOT NULL,
    source_channel VARCHAR(32) NOT NULL,
    source_code VARCHAR(64),
    intent_course_id BIGINT,
    owner_user_id BIGINT,
    wecom_external_user_id VARCHAR(64),
    status VARCHAR(32) NOT NULL,
    match_exception_flag TINYINT(1) NOT NULL DEFAULT 0,
    next_follow_at DATETIME(3),
    latest_follow_at DATETIME(3),
    student_id BIGINT,
    converted_order_id BIGINT,
    converted_at DATETIME(3),
    abandon_reason TEXT,
    created_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    created_by BIGINT,
    updated_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    updated_by BIGINT,
    version BIGINT NOT NULL DEFAULT 0,
    deleted_flag TINYINT(1) NOT NULL DEFAULT 0,
    deleted_at DATETIME(3),
    deleted_by BIGINT,
    PRIMARY KEY (id),
    UNIQUE KEY uk_crm_lead_no (lead_no),
    KEY idx_lead_mobile (mobile),
    KEY idx_lead_owner_status (owner_user_id, status),
    KEY idx_lead_student (student_id),
    KEY idx_lead_converted_order (converted_order_id),
    KEY idx_lead_next_follow (next_follow_at),
    CONSTRAINT chk_crm_lead_status CHECK (status IN ('PENDING_FOLLOW', 'CONTACTED', 'CONVERTED', 'ABANDONED'))
);

CREATE TABLE IF NOT EXISTS edu_student (
    id BIGINT NOT NULL,
    student_no VARCHAR(32) NOT NULL,
    user_id BIGINT,
    mobile VARCHAR(32),
    nickname VARCHAR(64),
    real_name VARCHAR(64),
    wx_openid VARCHAR(64),
    wx_unionid VARCHAR(64),
    wecom_external_user_id VARCHAR(64),
    primary_lead_id BIGINT,
    status VARCHAR(32) NOT NULL,
    merged_to_student_id BIGINT,
    tags JSON,
    created_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    created_by BIGINT,
    updated_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    updated_by BIGINT,
    version BIGINT NOT NULL DEFAULT 0,
    deleted_flag TINYINT(1) NOT NULL DEFAULT 0,
    deleted_at DATETIME(3),
    deleted_by BIGINT,
    PRIMARY KEY (id),
    UNIQUE KEY uk_student_no (student_no),
    UNIQUE KEY uk_student_user_id (user_id),
    UNIQUE KEY uk_student_mobile (mobile),
    UNIQUE KEY uk_student_wx_openid (wx_openid),
    KEY idx_student_unionid (wx_unionid),
    KEY idx_student_external_user (wecom_external_user_id),
    KEY idx_student_primary_lead (primary_lead_id),
    KEY idx_student_status (status)
);

CREATE TABLE IF NOT EXISTS student_address (
    id BIGINT NOT NULL,
    student_id BIGINT NOT NULL,
    receiver_name VARCHAR(64) NOT NULL,
    receiver_mobile VARCHAR(32) NOT NULL,
    province VARCHAR(64) NOT NULL,
    city VARCHAR(64) NOT NULL,
    district VARCHAR(64) NOT NULL,
    detail_address VARCHAR(255) NOT NULL,
    postal_code VARCHAR(16),
    is_default TINYINT(1) NOT NULL DEFAULT 0,
    status VARCHAR(32) NOT NULL,
    created_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    created_by BIGINT,
    updated_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    updated_by BIGINT,
    version BIGINT NOT NULL DEFAULT 0,
    deleted_flag TINYINT(1) NOT NULL DEFAULT 0,
    deleted_at DATETIME(3),
    deleted_by BIGINT,
    PRIMARY KEY (id),
    KEY idx_address_student (student_id),
    KEY idx_address_status (status)
);

CREATE TABLE IF NOT EXISTS student_invoice_title (
    id BIGINT NOT NULL,
    student_id BIGINT NOT NULL,
    title_type VARCHAR(32) NOT NULL,
    title_name VARCHAR(128) NOT NULL,
    tax_no VARCHAR(64),
    email VARCHAR(128),
    is_default TINYINT(1) NOT NULL DEFAULT 0,
    status VARCHAR(32) NOT NULL,
    created_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    created_by BIGINT,
    updated_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    updated_by BIGINT,
    version BIGINT NOT NULL DEFAULT 0,
    deleted_flag TINYINT(1) NOT NULL DEFAULT 0,
    deleted_at DATETIME(3),
    deleted_by BIGINT,
    PRIMARY KEY (id),
    KEY idx_title_student (student_id),
    KEY idx_title_tax_no (tax_no)
);

CREATE TABLE IF NOT EXISTS course (
    id BIGINT NOT NULL,
    course_no VARCHAR(32) NOT NULL,
    course_title VARCHAR(128) NOT NULL,
    course_type VARCHAR(32) NOT NULL,
    cover_url VARCHAR(255),
    summary TEXT,
    detail TEXT,
    teacher_user_id BIGINT,
    category_code VARCHAR(64),
    course_group_qr VARCHAR(255),
    default_tax_rule_id BIGINT,
    status VARCHAR(32) NOT NULL,
    sale_start_at DATETIME(3),
    sale_end_at DATETIME(3),
    published_at DATETIME(3),
    delete_notice_deadline DATETIME(3),
    created_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    created_by BIGINT,
    updated_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    updated_by BIGINT,
    version BIGINT NOT NULL DEFAULT 0,
    deleted_flag TINYINT(1) NOT NULL DEFAULT 0,
    deleted_at DATETIME(3),
    deleted_by BIGINT,
    PRIMARY KEY (id),
    UNIQUE KEY uk_course_no (course_no),
    KEY idx_course_status_sale (status, sale_start_at, sale_end_at),
    KEY idx_course_teacher (teacher_user_id),
    KEY idx_course_category (category_code),
    CONSTRAINT chk_course_status CHECK (status IN ('DRAFT', 'PENDING_REVIEW', 'ON_SHELF', 'OFF_SHELF', 'DELETE_PENDING', 'DELETED'))
);

CREATE TABLE IF NOT EXISTS course_spec (
    id BIGINT NOT NULL,
    spec_no VARCHAR(32) NOT NULL,
    course_id BIGINT NOT NULL,
    spec_name VARCHAR(128) NOT NULL,
    sale_price_cent BIGINT NOT NULL,
    origin_price_cent BIGINT,
    stock_mode VARCHAR(32) NOT NULL,
    contains_physical TINYINT(1) NOT NULL DEFAULT 0,
    sku_id BIGINT,
    gift_sku_id BIGINT,
    tax_rule_id BIGINT,
    amount_split_snapshot JSON,
    status VARCHAR(32) NOT NULL,
    sort_no INT NOT NULL DEFAULT 0,
    created_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    created_by BIGINT,
    updated_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    updated_by BIGINT,
    version BIGINT NOT NULL DEFAULT 0,
    deleted_flag TINYINT(1) NOT NULL DEFAULT 0,
    deleted_at DATETIME(3),
    deleted_by BIGINT,
    PRIMARY KEY (id),
    UNIQUE KEY uk_course_spec_no (spec_no),
    UNIQUE KEY uk_course_spec_course_name (course_id, spec_name),
    KEY idx_spec_course_status (course_id, status),
    KEY idx_spec_sku (sku_id),
    KEY idx_spec_tax_rule (tax_rule_id),
    CONSTRAINT chk_course_spec_status CHECK (status IN ('ENABLED', 'DISABLED')),
    CONSTRAINT chk_course_spec_sale_price CHECK (sale_price_cent >= 0),
    CONSTRAINT chk_course_spec_origin_price CHECK (origin_price_cent IS NULL OR origin_price_cent >= 0)
);

CREATE TABLE IF NOT EXISTS course_lesson_node (
    id BIGINT NOT NULL,
    course_id BIGINT NOT NULL,
    parent_node_id BIGINT,
    node_type VARCHAR(32) NOT NULL,
    title VARCHAR(128) NOT NULL,
    lesson_type VARCHAR(32),
    live_start_at DATETIME(3),
    live_end_at DATETIME(3),
    replay_url VARCHAR(255),
    resource_file VARCHAR(255),
    status VARCHAR(32) NOT NULL,
    sort_no INT NOT NULL DEFAULT 0,
    remind_enabled TINYINT(1) NOT NULL DEFAULT 0,
    created_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    created_by BIGINT,
    updated_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    updated_by BIGINT,
    version BIGINT NOT NULL DEFAULT 0,
    deleted_flag TINYINT(1) NOT NULL DEFAULT 0,
    deleted_at DATETIME(3),
    deleted_by BIGINT,
    PRIMARY KEY (id),
    UNIQUE KEY uk_lesson_course_parent_sort (course_id, parent_node_id, sort_no),
    KEY idx_lesson_course_parent (course_id, parent_node_id),
    KEY idx_lesson_status (status),
    KEY idx_lesson_live_time (live_start_at, live_end_at),
    CONSTRAINT chk_lesson_node_type CHECK (node_type IN ('CHAPTER', 'LESSON')),
    CONSTRAINT chk_lesson_status CHECK (status IN ('DRAFT', 'PUBLISHED', 'HIDDEN'))
);

CREATE TABLE IF NOT EXISTS learning_entitlement (
    id BIGINT NOT NULL,
    entitlement_no VARCHAR(32) NOT NULL,
    student_id BIGINT NOT NULL,
    user_id BIGINT NOT NULL,
    order_id BIGINT NOT NULL,
    order_no VARCHAR(32) NOT NULL,
    order_item_id BIGINT NOT NULL,
    course_id BIGINT NOT NULL,
    spec_id BIGINT NOT NULL,
    status VARCHAR(32) NOT NULL,
    opened_at DATETIME(3),
    frozen_at DATETIME(3),
    revoked_at DATETIME(3),
    expire_at DATETIME(3),
    source_refund_id BIGINT,
    remind_stopped TINYINT(1) NOT NULL DEFAULT 0,
    course_snapshot JSON NOT NULL,
    created_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    created_by BIGINT,
    updated_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    updated_by BIGINT,
    version BIGINT NOT NULL DEFAULT 0,
    PRIMARY KEY (id),
    UNIQUE KEY uk_entitlement_no (entitlement_no),
    UNIQUE KEY uk_entitlement_student_order_course (student_id, order_id, course_id),
    KEY idx_entitlement_student_status (student_id, status),
    KEY idx_entitlement_order (order_id),
    KEY idx_entitlement_course (course_id),
    KEY idx_entitlement_refund (source_refund_id),
    CONSTRAINT chk_entitlement_status CHECK (status IN ('ACTIVE', 'FROZEN', 'REVOKED'))
);

CREATE TABLE IF NOT EXISTS trade_order (
    id BIGINT NOT NULL,
    order_no VARCHAR(32) NOT NULL,
    merchant_order_no VARCHAR(64) NOT NULL,
    student_id BIGINT NOT NULL,
    user_id BIGINT NOT NULL,
    lead_id BIGINT,
    source_channel VARCHAR(32) NOT NULL,
    total_amount_cent BIGINT NOT NULL,
    discount_amount_cent BIGINT NOT NULL DEFAULT 0,
    payable_amount_cent BIGINT NOT NULL,
    paid_amount_cent BIGINT,
    course_snapshot JSON NOT NULL,
    price_snapshot JSON NOT NULL,
    tax_snapshot JSON NOT NULL,
    receiver_snapshot JSON,
    payment_status VARCHAR(32) NOT NULL,
    fulfillment_status VARCHAR(32) NOT NULL,
    refund_status VARCHAR(32) NOT NULL,
    invoice_status VARCHAR(32) NOT NULL,
    payment_expire_at DATETIME(3) NOT NULL,
    paid_at DATETIME(3),
    closed_at DATETIME(3),
    close_reason TEXT,
    remark TEXT,
    created_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    created_by BIGINT,
    updated_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    updated_by BIGINT,
    version BIGINT NOT NULL DEFAULT 0,
    PRIMARY KEY (id),
    UNIQUE KEY uk_trade_order_no (order_no),
    UNIQUE KEY uk_trade_merchant_order_no (merchant_order_no),
    KEY idx_order_student_created (student_id, created_at),
    KEY idx_order_payment_status (payment_status),
    KEY idx_order_fulfillment_status (fulfillment_status),
    KEY idx_order_refund_status (refund_status),
    KEY idx_order_invoice_status (invoice_status),
    KEY idx_order_paid_at (paid_at),
    KEY idx_order_lead (lead_id),
    CONSTRAINT chk_order_payment_status CHECK (payment_status IN ('PENDING', 'PAID', 'CLOSED')),
    CONSTRAINT chk_order_fulfillment_status CHECK (fulfillment_status IN ('NO_SHIPMENT', 'PENDING_SHIPMENT', 'SHIPPED', 'SIGNED')),
    CONSTRAINT chk_order_refund_status CHECK (refund_status IN ('NONE', 'REVIEWING', 'REJECTED', 'PROCESSING', 'MANUAL_REQUIRED', 'FAILED', 'REFUNDED')),
    CONSTRAINT chk_order_invoice_status CHECK (invoice_status IN ('NOT_APPLIED', 'APPLIED', 'TO_BE_ISSUED', 'ISSUED', 'RED_REVERSED')),
    CONSTRAINT chk_order_amounts CHECK (total_amount_cent >= 0 AND discount_amount_cent >= 0 AND payable_amount_cent >= 0 AND (paid_amount_cent IS NULL OR paid_amount_cent >= 0))
);

CREATE TABLE IF NOT EXISTS trade_order_item (
    id BIGINT NOT NULL,
    order_id BIGINT NOT NULL,
    order_no VARCHAR(32) NOT NULL,
    line_no INT NOT NULL,
    course_id BIGINT NOT NULL,
    spec_id BIGINT NOT NULL,
    item_name VARCHAR(128) NOT NULL,
    quantity INT NOT NULL,
    unit_price_cent BIGINT NOT NULL,
    total_amount_cent BIGINT NOT NULL,
    discount_amount_cent BIGINT NOT NULL DEFAULT 0,
    payable_amount_cent BIGINT NOT NULL,
    paid_amount_cent BIGINT,
    contains_physical TINYINT(1) NOT NULL DEFAULT 0,
    sku_id BIGINT,
    gift_sku_id BIGINT,
    course_snapshot JSON NOT NULL,
    spec_snapshot JSON NOT NULL,
    tax_snapshot JSON NOT NULL,
    created_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    created_by BIGINT,
    updated_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    updated_by BIGINT,
    version BIGINT NOT NULL DEFAULT 0,
    PRIMARY KEY (id),
    UNIQUE KEY uk_order_item_line (order_id, line_no),
    KEY idx_order_item_order (order_id),
    KEY idx_order_item_course_spec (course_id, spec_id),
    KEY idx_order_item_sku (sku_id),
    CONSTRAINT chk_order_item_quantity CHECK (quantity > 0),
    CONSTRAINT chk_order_item_amounts CHECK (unit_price_cent >= 0 AND total_amount_cent >= 0 AND discount_amount_cent >= 0 AND payable_amount_cent >= 0 AND (paid_amount_cent IS NULL OR paid_amount_cent >= 0))
);

CREATE TABLE IF NOT EXISTS order_document_link (
    id BIGINT NOT NULL,
    order_id BIGINT NOT NULL,
    order_no VARCHAR(32) NOT NULL,
    document_type VARCHAR(32) NOT NULL,
    document_id BIGINT NOT NULL,
    document_no VARCHAR(64) NOT NULL,
    document_status VARCHAR(32) NOT NULL,
    amount_cent BIGINT,
    relation_type VARCHAR(32) NOT NULL,
    occurred_at DATETIME(3) NOT NULL,
    source_table VARCHAR(64) NOT NULL,
    remark TEXT,
    created_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    created_by BIGINT,
    updated_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    updated_by BIGINT,
    version BIGINT NOT NULL DEFAULT 0,
    PRIMARY KEY (id),
    UNIQUE KEY uk_doc_link_order_document (order_id, document_type, document_id),
    KEY idx_doc_link_order_type_time (order_id, document_type, occurred_at),
    KEY idx_doc_link_document (document_type, document_id),
    KEY idx_doc_link_status (document_status),
    CONSTRAINT chk_doc_link_amount CHECK (amount_cent IS NULL OR amount_cent >= 0)
);

CREATE TABLE IF NOT EXISTS pay_payment (
    id BIGINT NOT NULL,
    payment_no VARCHAR(32) NOT NULL,
    order_id BIGINT NOT NULL,
    order_no VARCHAR(32) NOT NULL,
    merchant_order_no VARCHAR(64) NOT NULL,
    channel VARCHAR(32) NOT NULL,
    payment_method VARCHAR(32) NOT NULL,
    payment_result VARCHAR(32) NOT NULL,
    paid_amount_cent BIGINT NOT NULL,
    external_payment_no VARCHAR(64),
    paid_at DATETIME(3),
    callback_event_no VARCHAR(64),
    idempotency_key VARCHAR(128) NOT NULL,
    failure_reason TEXT,
    raw_callback_snapshot JSON,
    created_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    created_by BIGINT,
    updated_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    updated_by BIGINT,
    version BIGINT NOT NULL DEFAULT 0,
    PRIMARY KEY (id),
    UNIQUE KEY uk_payment_no (payment_no),
    UNIQUE KEY uk_payment_external_no (external_payment_no),
    UNIQUE KEY uk_payment_idempotency (idempotency_key),
    KEY idx_payment_order (order_id),
    KEY idx_payment_merchant_order (merchant_order_no),
    KEY idx_payment_result_paid_at (payment_result, paid_at),
    KEY idx_payment_callback_event (callback_event_no),
    CONSTRAINT chk_payment_result CHECK (payment_result IN ('SUCCESS', 'FAILED', 'PROCESSING', 'CLOSED')),
    CONSTRAINT chk_payment_amount CHECK (paid_amount_cent >= 0)
);

CREATE TABLE IF NOT EXISTS pay_refund (
    id BIGINT NOT NULL,
    refund_no VARCHAR(32) NOT NULL,
    order_id BIGINT NOT NULL,
    order_no VARCHAR(32) NOT NULL,
    payment_id BIGINT NOT NULL,
    student_id BIGINT NOT NULL,
    apply_amount_cent BIGINT NOT NULL,
    approved_amount_cent BIGINT,
    refund_reason VARCHAR(128) NOT NULL,
    apply_description TEXT,
    status VARCHAR(32) NOT NULL,
    reviewer_user_id BIGINT,
    review_comment TEXT,
    reject_reason TEXT,
    refund_channel VARCHAR(32),
    external_refund_no VARCHAR(64),
    manual_voucher_no VARCHAR(64),
    manual_voucher_file VARCHAR(255),
    failure_reason TEXT,
    refunded_at DATETIME(3),
    entitlement_action VARCHAR(32),
    need_return_goods TINYINT(1) NOT NULL DEFAULT 0,
    idempotency_key VARCHAR(128) NOT NULL,
    created_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    created_by BIGINT,
    updated_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    updated_by BIGINT,
    version BIGINT NOT NULL DEFAULT 0,
    PRIMARY KEY (id),
    UNIQUE KEY uk_refund_no (refund_no),
    UNIQUE KEY uk_refund_external_no (external_refund_no),
    UNIQUE KEY uk_refund_idempotency (idempotency_key),
    KEY idx_refund_by_order_and_status (order_id, status),
    KEY idx_refund_student (student_id),
    KEY idx_refund_payment (payment_id),
    KEY idx_refund_refunded_at (refunded_at),
    CONSTRAINT chk_refund_status CHECK (status IN ('REVIEWING', 'REJECTED', 'PROCESSING', 'MANUAL_REQUIRED', 'FAILED', 'REFUNDED')),
    CONSTRAINT chk_refund_amounts CHECK (apply_amount_cent >= 0 AND (approved_amount_cent IS NULL OR approved_amount_cent >= 0))
);

CREATE TABLE IF NOT EXISTS pay_refund_item (
    id BIGINT NOT NULL,
    refund_id BIGINT NOT NULL,
    refund_no VARCHAR(32) NOT NULL,
    order_id BIGINT NOT NULL,
    order_item_id BIGINT NOT NULL,
    course_id BIGINT NOT NULL,
    spec_id BIGINT NOT NULL,
    refund_quantity INT NOT NULL,
    refund_amount_cent BIGINT NOT NULL,
    item_snapshot JSON NOT NULL,
    created_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    created_by BIGINT,
    updated_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    updated_by BIGINT,
    version BIGINT NOT NULL DEFAULT 0,
    PRIMARY KEY (id),
    UNIQUE KEY uk_refund_item_order_item (refund_id, order_item_id),
    KEY idx_refund_item_refund (refund_id),
    KEY idx_refund_item_order (order_id),
    CONSTRAINT chk_refund_item_quantity CHECK (refund_quantity > 0),
    CONSTRAINT chk_refund_item_amount CHECK (refund_amount_cent >= 0)
);

CREATE TABLE IF NOT EXISTS fulfillment_shipment (
    id BIGINT NOT NULL,
    shipment_no VARCHAR(32) NOT NULL,
    order_id BIGINT NOT NULL,
    order_no VARCHAR(32) NOT NULL,
    student_id BIGINT NOT NULL,
    status VARCHAR(32) NOT NULL,
    receiver_snapshot JSON NOT NULL,
    logistics_company_code VARCHAR(64),
    logistics_company_name VARCHAR(64),
    tracking_no VARCHAR(64),
    waybill_file VARCHAR(255),
    shipped_at DATETIME(3),
    shipper_user_id BIGINT,
    signed_at DATETIME(3),
    exception_flag TINYINT(1) NOT NULL DEFAULT 0,
    exception_reason TEXT,
    created_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    created_by BIGINT,
    updated_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    updated_by BIGINT,
    version BIGINT NOT NULL DEFAULT 0,
    PRIMARY KEY (id),
    UNIQUE KEY uk_shipment_no (shipment_no),
    UNIQUE KEY uk_shipment_tracking_no (tracking_no),
    KEY idx_shipment_order (order_id),
    KEY idx_shipment_student (student_id),
    KEY idx_shipment_status (status),
    KEY idx_shipment_shipped_at (shipped_at),
    KEY idx_shipment_exception (exception_flag),
    CONSTRAINT chk_shipment_status CHECK (status IN ('PENDING_SHIPMENT', 'SHIPPED', 'SIGNED'))
);

CREATE TABLE IF NOT EXISTS fulfillment_shipment_item (
    id BIGINT NOT NULL,
    shipment_id BIGINT NOT NULL,
    shipment_no VARCHAR(32) NOT NULL,
    order_id BIGINT NOT NULL,
    order_item_id BIGINT,
    sku_id BIGINT NOT NULL,
    sku_no VARCHAR(32) NOT NULL,
    sku_name VARCHAR(128) NOT NULL,
    line_type VARCHAR(32) NOT NULL,
    quantity INT NOT NULL,
    stock_flow_id BIGINT,
    created_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    created_by BIGINT,
    updated_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    updated_by BIGINT,
    version BIGINT NOT NULL DEFAULT 0,
    PRIMARY KEY (id),
    UNIQUE KEY uk_shipment_item_sku_line (shipment_id, sku_id, line_type),
    KEY idx_shipment_item_shipment (shipment_id),
    KEY idx_shipment_item_order (order_id),
    KEY idx_shipment_item_sku (sku_id),
    CONSTRAINT chk_shipment_item_quantity CHECK (quantity > 0)
);

CREATE TABLE IF NOT EXISTS logistics_trace (
    id BIGINT NOT NULL,
    shipment_id BIGINT NOT NULL,
    order_id BIGINT NOT NULL,
    tracking_no VARCHAR(64) NOT NULL,
    logistics_node_time DATETIME(3) NOT NULL,
    node_status VARCHAR(32) NOT NULL,
    node_desc VARCHAR(255),
    raw_snapshot JSON,
    created_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    PRIMARY KEY (id),
    UNIQUE KEY uk_logistics_tracking_node (tracking_no, logistics_node_time, node_status),
    KEY idx_logistics_shipment_time (shipment_id, logistics_node_time),
    KEY idx_logistics_order_time (order_id, logistics_node_time)
);

CREATE TABLE IF NOT EXISTS inventory_sku (
    id BIGINT NOT NULL,
    sku_no VARCHAR(32) NOT NULL,
    sku_name VARCHAR(128) NOT NULL,
    category_code VARCHAR(64),
    sku_type VARCHAR(32) NOT NULL,
    unit VARCHAR(16) NOT NULL,
    spec_attrs JSON,
    spec_attrs_hash VARCHAR(64) NOT NULL,
    default_supplier_id BIGINT,
    cost_price_cent BIGINT,
    current_stock INT NOT NULL DEFAULT 0,
    locked_stock INT NOT NULL DEFAULT 0,
    available_stock INT NOT NULL DEFAULT 0,
    safety_stock INT NOT NULL DEFAULT 0,
    status VARCHAR(32) NOT NULL,
    image_url VARCHAR(255),
    created_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    created_by BIGINT,
    updated_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    updated_by BIGINT,
    version BIGINT NOT NULL DEFAULT 0,
    deleted_flag TINYINT(1) NOT NULL DEFAULT 0,
    deleted_at DATETIME(3),
    deleted_by BIGINT,
    PRIMARY KEY (id),
    UNIQUE KEY uk_inventory_sku_no (sku_no),
    UNIQUE KEY uk_inventory_sku_name_attrs (sku_name, spec_attrs_hash),
    KEY idx_sku_supplier (default_supplier_id),
    KEY idx_sku_status (status),
    KEY idx_sku_category (category_code),
    KEY idx_sku_safety_stock (safety_stock),
    CONSTRAINT chk_sku_cost_price CHECK (cost_price_cent IS NULL OR cost_price_cent >= 0),
    CONSTRAINT chk_sku_stock CHECK (current_stock >= 0 AND locked_stock >= 0 AND available_stock >= 0 AND safety_stock >= 0)
);

CREATE TABLE IF NOT EXISTS inventory_stock_flow (
    id BIGINT NOT NULL,
    flow_no VARCHAR(32) NOT NULL,
    sku_id BIGINT NOT NULL,
    biz_type VARCHAR(32) NOT NULL,
    biz_id BIGINT NOT NULL,
    biz_no VARCHAR(64) NOT NULL,
    order_id BIGINT,
    shipment_id BIGINT,
    purchase_id BIGINT,
    direction VARCHAR(32) NOT NULL,
    quantity INT NOT NULL,
    before_stock INT NOT NULL,
    after_stock INT NOT NULL,
    operator_user_id BIGINT,
    occurred_at DATETIME(3) NOT NULL,
    idempotency_key VARCHAR(128) NOT NULL,
    remark TEXT,
    PRIMARY KEY (id),
    UNIQUE KEY uk_stock_flow_no (flow_no),
    UNIQUE KEY uk_stock_flow_idempotency (idempotency_key),
    KEY idx_stock_flow_sku_time (sku_id, occurred_at),
    KEY idx_stock_flow_order (order_id),
    KEY idx_stock_flow_shipment (shipment_id),
    KEY idx_stock_flow_purchase (purchase_id),
    KEY idx_stock_flow_biz (biz_type, biz_id),
    CONSTRAINT chk_stock_flow_quantity CHECK (quantity > 0)
);

CREATE TABLE IF NOT EXISTS supplier (
    id BIGINT NOT NULL,
    supplier_no VARCHAR(32) NOT NULL,
    supplier_name VARCHAR(128) NOT NULL,
    short_name VARCHAR(64),
    contact_name VARCHAR(64) NOT NULL,
    contact_mobile VARCHAR(32) NOT NULL,
    contact_email VARCHAR(128),
    tax_no VARCHAR(64),
    address TEXT,
    settlement_method VARCHAR(128),
    access_status VARCHAR(32) NOT NULL,
    status VARCHAR(32) NOT NULL,
    created_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    created_by BIGINT,
    updated_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    updated_by BIGINT,
    version BIGINT NOT NULL DEFAULT 0,
    deleted_flag TINYINT(1) NOT NULL DEFAULT 0,
    deleted_at DATETIME(3),
    deleted_by BIGINT,
    PRIMARY KEY (id),
    UNIQUE KEY uk_supplier_no (supplier_no),
    UNIQUE KEY uk_supplier_name (supplier_name),
    KEY idx_supplier_status (status),
    KEY idx_supplier_access_status (access_status),
    KEY idx_supplier_tax_no (tax_no)
);

CREATE TABLE IF NOT EXISTS supplier_sku (
    id BIGINT NOT NULL,
    supplier_id BIGINT NOT NULL,
    sku_id BIGINT NOT NULL,
    supplier_sku_no VARCHAR(64),
    purchase_price_cent BIGINT NOT NULL,
    min_order_qty INT NOT NULL DEFAULT 1,
    lead_days INT NOT NULL DEFAULT 0,
    status VARCHAR(32) NOT NULL,
    created_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    created_by BIGINT,
    updated_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    updated_by BIGINT,
    version BIGINT NOT NULL DEFAULT 0,
    PRIMARY KEY (id),
    UNIQUE KEY uk_supplier_sku_supplier_sku (supplier_id, sku_id),
    KEY idx_supplier_sku_supplier (supplier_id),
    KEY idx_supplier_sku_sku (sku_id),
    KEY idx_supplier_sku_status (status),
    CONSTRAINT chk_supplier_sku_price CHECK (purchase_price_cent >= 0),
    CONSTRAINT chk_supplier_sku_qty CHECK (min_order_qty > 0 AND lead_days >= 0)
);

CREATE TABLE IF NOT EXISTS purchase_order (
    id BIGINT NOT NULL,
    purchase_no VARCHAR(32) NOT NULL,
    supplier_id BIGINT NOT NULL,
    applicant_user_id BIGINT NOT NULL,
    total_amount_cent BIGINT NOT NULL,
    purchase_status VARCHAR(32) NOT NULL,
    input_invoice_status VARCHAR(32) NOT NULL,
    approval_id BIGINT,
    threshold_snapshot_cent BIGINT,
    expected_arrival_date DATE,
    supplier_confirm_at DATETIME(3),
    supplier_reject_reason TEXT,
    logistics_company_name VARCHAR(64),
    tracking_no VARCHAR(64),
    received_at DATETIME(3),
    receiver_user_id BIGINT,
    cancel_reason TEXT,
    input_invoice_no VARCHAR(64),
    input_invoice_amount_cent BIGINT,
    input_invoice_file VARCHAR(255),
    created_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    created_by BIGINT,
    updated_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    updated_by BIGINT,
    version BIGINT NOT NULL DEFAULT 0,
    PRIMARY KEY (id),
    UNIQUE KEY uk_purchase_no (purchase_no),
    KEY idx_purchase_supplier_status (supplier_id, purchase_status),
    KEY idx_purchase_applicant (applicant_user_id),
    KEY idx_purchase_approval (approval_id),
    KEY idx_purchase_tracking_no (tracking_no),
    KEY idx_purchase_received_at (received_at),
    CONSTRAINT chk_purchase_status CHECK (purchase_status IN ('APPROVING', 'APPROVAL_REJECTED', 'WAIT_CONFIRM', 'CONFIRMED', 'SHIPPED', 'REJECTED', 'COMPLETED', 'CANCELED')),
    CONSTRAINT chk_purchase_input_invoice_status CHECK (input_invoice_status IN ('NOT_INVOICED', 'INVOICED')),
    CONSTRAINT chk_purchase_amounts CHECK (total_amount_cent >= 0 AND (threshold_snapshot_cent IS NULL OR threshold_snapshot_cent >= 0) AND (input_invoice_amount_cent IS NULL OR input_invoice_amount_cent >= 0))
);

CREATE TABLE IF NOT EXISTS purchase_order_item (
    id BIGINT NOT NULL,
    purchase_id BIGINT NOT NULL,
    purchase_no VARCHAR(32) NOT NULL,
    line_no INT NOT NULL,
    sku_id BIGINT NOT NULL,
    sku_no VARCHAR(32) NOT NULL,
    sku_name VARCHAR(128) NOT NULL,
    quantity INT NOT NULL,
    unit_price_cent BIGINT NOT NULL,
    total_amount_cent BIGINT NOT NULL,
    received_quantity INT NOT NULL DEFAULT 0,
    created_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    created_by BIGINT,
    updated_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    updated_by BIGINT,
    version BIGINT NOT NULL DEFAULT 0,
    PRIMARY KEY (id),
    UNIQUE KEY uk_purchase_item_line (purchase_id, line_no),
    KEY idx_purchase_item_purchase (purchase_id),
    KEY idx_purchase_item_sku (sku_id),
    CONSTRAINT chk_purchase_item_quantity CHECK (quantity > 0 AND received_quantity >= 0),
    CONSTRAINT chk_purchase_item_amounts CHECK (unit_price_cent >= 0 AND total_amount_cent >= 0)
);

CREATE TABLE IF NOT EXISTS purchase_receipt (
    id BIGINT NOT NULL,
    receipt_no VARCHAR(32) NOT NULL,
    purchase_id BIGINT NOT NULL,
    purchase_no VARCHAR(32) NOT NULL,
    inbound_batch_no VARCHAR(64) NOT NULL,
    status VARCHAR(32) NOT NULL,
    received_at DATETIME(3) NOT NULL,
    receiver_user_id BIGINT NOT NULL,
    stock_flow_ids JSON,
    remark TEXT,
    created_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    created_by BIGINT,
    updated_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    updated_by BIGINT,
    version BIGINT NOT NULL DEFAULT 0,
    PRIMARY KEY (id),
    UNIQUE KEY uk_purchase_receipt_no (receipt_no),
    UNIQUE KEY uk_purchase_receipt_batch (purchase_no, inbound_batch_no),
    KEY idx_receipt_purchase (purchase_id),
    KEY idx_receipt_received_at (received_at)
);

CREATE TABLE IF NOT EXISTS tax_rule (
    id BIGINT NOT NULL,
    rule_no VARCHAR(32) NOT NULL,
    rule_name VARCHAR(64) NOT NULL,
    tax_category VARCHAR(64) NOT NULL,
    tax_rate DECIMAL(10,4) NOT NULL,
    invoice_item_name VARCHAR(128) NOT NULL,
    status VARCHAR(32) NOT NULL,
    description TEXT,
    created_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    created_by BIGINT,
    updated_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    updated_by BIGINT,
    version BIGINT NOT NULL DEFAULT 0,
    deleted_flag TINYINT(1) NOT NULL DEFAULT 0,
    deleted_at DATETIME(3),
    deleted_by BIGINT,
    PRIMARY KEY (id),
    UNIQUE KEY uk_tax_rule_no (rule_no),
    UNIQUE KEY uk_tax_rule_name (rule_name),
    KEY idx_tax_rule_status (status),
    KEY idx_tax_rule_category (tax_category),
    CONSTRAINT chk_tax_rule_rate CHECK (tax_rate >= 0)
);

CREATE TABLE IF NOT EXISTS tax_invoice (
    id BIGINT NOT NULL,
    invoice_apply_no VARCHAR(32) NOT NULL,
    order_id BIGINT NOT NULL,
    order_no VARCHAR(32) NOT NULL,
    student_id BIGINT NOT NULL,
    title_type VARCHAR(32) NOT NULL,
    title_name VARCHAR(128) NOT NULL,
    tax_no VARCHAR(64),
    email VARCHAR(128),
    invoice_amount_cent BIGINT NOT NULL,
    tax_amount_cent BIGINT,
    tax_rule_snapshot JSON NOT NULL,
    status VARCHAR(32) NOT NULL,
    invoice_channel VARCHAR(32),
    invoice_no VARCHAR(64),
    invoice_file VARCHAR(255),
    issued_at DATETIME(3),
    source_refund_id BIGINT,
    red_invoice_no VARCHAR(64),
    red_invoice_file VARCHAR(255),
    red_reversed_at DATETIME(3),
    failure_reason TEXT,
    created_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    created_by BIGINT,
    updated_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    updated_by BIGINT,
    version BIGINT NOT NULL DEFAULT 0,
    PRIMARY KEY (id),
    UNIQUE KEY uk_invoice_apply_no (invoice_apply_no),
    UNIQUE KEY uk_invoice_no (invoice_no),
    UNIQUE KEY uk_invoice_red_no (red_invoice_no),
    KEY idx_invoice_by_order_and_status (order_id, status),
    KEY idx_invoice_student (student_id),
    KEY idx_invoice_issued_at (issued_at),
    KEY idx_invoice_refund (source_refund_id),
    KEY idx_invoice_status (status),
    CONSTRAINT chk_invoice_status CHECK (status IN ('APPLIED', 'TO_BE_ISSUED', 'ISSUED', 'RED_REVERSED')),
    CONSTRAINT chk_invoice_amounts CHECK (invoice_amount_cent >= 0 AND (tax_amount_cent IS NULL OR tax_amount_cent >= 0))
);

CREATE TABLE IF NOT EXISTS tax_invoice_item (
    id BIGINT NOT NULL,
    invoice_id BIGINT NOT NULL,
    invoice_apply_no VARCHAR(32) NOT NULL,
    order_id BIGINT NOT NULL,
    order_item_id BIGINT NOT NULL,
    item_name VARCHAR(128) NOT NULL,
    item_type VARCHAR(32) NOT NULL,
    amount_cent BIGINT NOT NULL,
    tax_rate DECIMAL(10,4) NOT NULL,
    tax_amount_cent BIGINT NOT NULL,
    tax_rule_id BIGINT,
    tax_snapshot JSON NOT NULL,
    created_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    created_by BIGINT,
    updated_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    updated_by BIGINT,
    version BIGINT NOT NULL DEFAULT 0,
    PRIMARY KEY (id),
    UNIQUE KEY uk_invoice_item_order_item_type (invoice_id, order_item_id, item_type),
    KEY idx_invoice_item_invoice (invoice_id),
    KEY idx_invoice_item_order (order_id),
    KEY idx_invoice_item_tax_rule (tax_rule_id),
    CONSTRAINT chk_invoice_item_amounts CHECK (amount_cent >= 0 AND tax_amount_cent >= 0 AND tax_rate >= 0)
);

CREATE TABLE IF NOT EXISTS finance_reconciliation_batch (
    id BIGINT NOT NULL,
    batch_no VARCHAR(32) NOT NULL,
    bill_month VARCHAR(7) NOT NULL,
    bill_source VARCHAR(32) NOT NULL,
    file_name VARCHAR(255) NOT NULL,
    file_digest VARCHAR(128) NOT NULL,
    import_status VARCHAR(32) NOT NULL,
    total_count INT NOT NULL DEFAULT 0,
    matched_count INT NOT NULL DEFAULT 0,
    diff_count INT NOT NULL DEFAULT 0,
    imported_by BIGINT,
    imported_at DATETIME(3),
    failure_reason TEXT,
    created_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    created_by BIGINT,
    updated_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    updated_by BIGINT,
    version BIGINT NOT NULL DEFAULT 0,
    PRIMARY KEY (id),
    UNIQUE KEY uk_recon_batch_no (batch_no),
    UNIQUE KEY uk_recon_batch_file (bill_month, bill_source, file_digest),
    KEY idx_recon_batch_month_source (bill_month, bill_source),
    KEY idx_recon_batch_status (import_status),
    KEY idx_recon_batch_imported_at (imported_at)
);

CREATE TABLE IF NOT EXISTS finance_reconciliation_record (
    id BIGINT NOT NULL,
    batch_id BIGINT NOT NULL,
    batch_no VARCHAR(32) NOT NULL,
    bill_month VARCHAR(7) NOT NULL,
    bill_source VARCHAR(32) NOT NULL,
    record_type VARCHAR(32) NOT NULL,
    order_id BIGINT,
    order_no VARCHAR(32),
    payment_id BIGINT,
    refund_id BIGINT,
    merchant_order_no VARCHAR(64),
    external_transaction_no VARCHAR(64),
    system_amount_cent BIGINT,
    bill_amount_cent BIGINT,
    fee_amount_cent BIGINT,
    result VARCHAR(32) NOT NULL,
    difference_reason TEXT,
    checked_flag TINYINT(1) NOT NULL DEFAULT 0,
    checked_by BIGINT,
    checked_at DATETIME(3),
    created_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    created_by BIGINT,
    updated_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    updated_by BIGINT,
    version BIGINT NOT NULL DEFAULT 0,
    PRIMARY KEY (id),
    UNIQUE KEY uk_recon_record_business (batch_no, record_type, merchant_order_no, external_transaction_no),
    KEY idx_recon_order (order_id),
    KEY idx_recon_payment (payment_id),
    KEY idx_recon_refund (refund_id),
    KEY idx_recon_result (result),
    KEY idx_recon_month_type (bill_month, record_type),
    KEY idx_recon_checked (checked_flag),
    CONSTRAINT chk_recon_result CHECK (result IN ('MATCHED', 'AMOUNT_DIFF', 'FEE_DIFF', 'UNMATCHED', 'DUPLICATE')),
    CONSTRAINT chk_recon_amounts CHECK ((system_amount_cent IS NULL OR system_amount_cent >= 0) AND (bill_amount_cent IS NULL OR bill_amount_cent >= 0) AND (fee_amount_cent IS NULL OR fee_amount_cent >= 0))
);

CREATE TABLE IF NOT EXISTS acct_material (
    id BIGINT NOT NULL,
    material_no VARCHAR(32) NOT NULL,
    material_type VARCHAR(32) NOT NULL,
    status VARCHAR(32) NOT NULL,
    related_month VARCHAR(7),
    order_id BIGINT,
    order_no VARCHAR(32),
    related_object_type VARCHAR(32),
    related_object_id BIGINT,
    related_object_no VARCHAR(64),
    request_user_id BIGINT NOT NULL,
    assignee_user_id BIGINT,
    purpose TEXT NOT NULL,
    due_at DATETIME(3),
    file_refs JSON,
    uploaded_by BIGINT,
    uploaded_at DATETIME(3),
    confirmed_by BIGINT,
    confirmed_at DATETIME(3),
    closed_reason TEXT,
    created_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    created_by BIGINT,
    updated_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    updated_by BIGINT,
    version BIGINT NOT NULL DEFAULT 0,
    PRIMARY KEY (id),
    UNIQUE KEY uk_material_no (material_no),
    KEY idx_material_order (order_id),
    KEY idx_material_month_type (related_month, material_type),
    KEY idx_material_status_due (status, due_at),
    KEY idx_material_related_object (related_object_type, related_object_id),
    KEY idx_material_assignee (assignee_user_id),
    CONSTRAINT chk_material_status CHECK (status IN ('PENDING_SUPPLEMENT', 'UPLOADED', 'CONFIRMED', 'CLOSED'))
);

CREATE TABLE IF NOT EXISTS acct_material_relation (
    id BIGINT NOT NULL,
    material_id BIGINT NOT NULL,
    material_no VARCHAR(32) NOT NULL,
    related_object_type VARCHAR(32) NOT NULL,
    related_object_id BIGINT NOT NULL,
    related_object_no VARCHAR(64) NOT NULL,
    order_id BIGINT,
    order_no VARCHAR(32),
    relation_role VARCHAR(32) NOT NULL,
    amount_cent BIGINT,
    created_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    PRIMARY KEY (id),
    UNIQUE KEY uk_material_rel_object (material_id, related_object_type, related_object_id),
    KEY idx_material_rel_material (material_id),
    KEY idx_material_rel_order (order_id),
    KEY idx_material_rel_object (related_object_type, related_object_id),
    CONSTRAINT chk_material_rel_amount CHECK (amount_cent IS NULL OR amount_cent >= 0)
);

CREATE TABLE IF NOT EXISTS notify_message (
    id BIGINT NOT NULL,
    notification_no VARCHAR(32) NOT NULL,
    receiver_user_id BIGINT,
    receiver_student_id BIGINT,
    channel VARCHAR(32) NOT NULL,
    scene_code VARCHAR(64) NOT NULL,
    template_code VARCHAR(64),
    title VARCHAR(128) NOT NULL,
    content TEXT NOT NULL,
    order_id BIGINT,
    related_object_type VARCHAR(32),
    related_object_id BIGINT,
    send_status VARCHAR(32) NOT NULL,
    read_status VARCHAR(32),
    sent_at DATETIME(3),
    read_at DATETIME(3),
    failure_reason TEXT,
    retry_count INT NOT NULL DEFAULT 0,
    idempotency_key VARCHAR(128) NOT NULL,
    created_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    created_by BIGINT,
    updated_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    updated_by BIGINT,
    version BIGINT NOT NULL DEFAULT 0,
    PRIMARY KEY (id),
    UNIQUE KEY uk_notify_no (notification_no),
    UNIQUE KEY uk_notify_idempotency_receiver (idempotency_key, channel, receiver_user_id),
    KEY idx_notify_receiver_status (receiver_user_id, send_status),
    KEY idx_notify_order (order_id),
    KEY idx_notify_related_object (related_object_type, related_object_id),
    KEY idx_notify_scene (scene_code),
    KEY idx_notify_send_status (send_status),
    CONSTRAINT chk_notify_channel CHECK (channel IN ('IN_APP', 'WECHAT_SUBSCRIBE', 'WECOM_CARD')),
    CONSTRAINT chk_notify_send_status CHECK (send_status IN ('PENDING', 'SENT', 'FAILED', 'CANCELED')),
    CONSTRAINT chk_notify_read_status CHECK (read_status IS NULL OR read_status IN ('UNREAD', 'READ')),
    CONSTRAINT chk_notify_retry_count CHECK (retry_count >= 0)
);

CREATE TABLE IF NOT EXISTS approval_record (
    id BIGINT NOT NULL,
    approval_no VARCHAR(32) NOT NULL,
    approval_type VARCHAR(32) NOT NULL,
    title VARCHAR(128) NOT NULL,
    applicant_user_id BIGINT NOT NULL,
    approver_user_id BIGINT,
    order_id BIGINT,
    related_object_type VARCHAR(32) NOT NULL,
    related_object_id BIGINT NOT NULL,
    related_object_no VARCHAR(64),
    status VARCHAR(32) NOT NULL,
    submit_reason TEXT,
    approval_comment TEXT,
    submitted_at DATETIME(3) NOT NULL,
    finished_at DATETIME(3),
    wecom_approval_id VARCHAR(64),
    amount_snapshot_cent BIGINT,
    created_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    created_by BIGINT,
    updated_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    updated_by BIGINT,
    version BIGINT NOT NULL DEFAULT 0,
    PRIMARY KEY (id),
    UNIQUE KEY uk_approval_no (approval_no),
    UNIQUE KEY uk_approval_wecom_id (wecom_approval_id),
    KEY idx_approval_applicant (applicant_user_id),
    KEY idx_approval_approver_status (approver_user_id, status),
    KEY idx_approval_related_object (related_object_type, related_object_id),
    KEY idx_approval_order (order_id),
    CONSTRAINT chk_approval_status CHECK (status IN ('PENDING', 'APPROVED', 'REJECTED', 'CANCELED')),
    CONSTRAINT chk_approval_amount CHECK (amount_snapshot_cent IS NULL OR amount_snapshot_cent >= 0)
);

CREATE TABLE IF NOT EXISTS sys_file_asset (
    id BIGINT NOT NULL,
    file_no VARCHAR(32) NOT NULL,
    file_name VARCHAR(255) NOT NULL,
    file_type VARCHAR(64) NOT NULL,
    storage_key VARCHAR(255) NOT NULL,
    access_url VARCHAR(255),
    file_digest VARCHAR(128) NOT NULL,
    file_size BIGINT NOT NULL,
    biz_type VARCHAR(32) NOT NULL,
    biz_id BIGINT NOT NULL,
    order_id BIGINT,
    status VARCHAR(32) NOT NULL,
    uploaded_by BIGINT,
    uploaded_at DATETIME(3),
    created_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    created_by BIGINT,
    updated_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    updated_by BIGINT,
    version BIGINT NOT NULL DEFAULT 0,
    PRIMARY KEY (id),
    UNIQUE KEY uk_file_no (file_no),
    UNIQUE KEY uk_file_digest_biz (file_digest, biz_type, biz_id),
    KEY idx_file_biz (biz_type, biz_id),
    KEY idx_file_order (order_id),
    KEY idx_file_uploaded_at (uploaded_at),
    CONSTRAINT chk_file_size CHECK (file_size >= 0)
);

CREATE TABLE IF NOT EXISTS integration_callback_event (
    id BIGINT NOT NULL,
    event_no VARCHAR(64) NOT NULL,
    source_system VARCHAR(32) NOT NULL,
    event_type VARCHAR(32) NOT NULL,
    idempotency_key VARCHAR(128) NOT NULL,
    order_id BIGINT,
    related_object_type VARCHAR(32),
    related_object_id BIGINT,
    related_object_no VARCHAR(64),
    processing_status VARCHAR(32) NOT NULL,
    retry_count INT NOT NULL DEFAULT 0,
    failure_reason TEXT,
    raw_snapshot JSON,
    received_at DATETIME(3) NOT NULL,
    processed_at DATETIME(3),
    PRIMARY KEY (id),
    UNIQUE KEY uk_callback_source_event (source_system, event_no),
    UNIQUE KEY uk_callback_idempotency (idempotency_key),
    KEY idx_callback_order (order_id),
    KEY idx_callback_related_object (related_object_type, related_object_id),
    KEY idx_callback_status_retry (processing_status, retry_count),
    KEY idx_callback_received_at (received_at),
    CONSTRAINT chk_callback_processing_status CHECK (processing_status IN ('PENDING', 'PROCESSED', 'FAILED', 'IGNORED')),
    CONSTRAINT chk_callback_retry_count CHECK (retry_count >= 0)
);

CREATE TABLE IF NOT EXISTS audit_operation_log (
    id BIGINT NOT NULL,
    trace_id VARCHAR(64),
    operator_user_id BIGINT,
    operator_name VARCHAR(64),
    operation_module VARCHAR(64) NOT NULL,
    operation_type VARCHAR(32) NOT NULL,
    target_type VARCHAR(32) NOT NULL,
    target_id BIGINT,
    target_no VARCHAR(64),
    order_id BIGINT,
    before_snapshot JSON,
    after_snapshot JSON,
    result VARCHAR(32) NOT NULL,
    failure_reason TEXT,
    client_ip VARCHAR(64),
    user_agent VARCHAR(255),
    occurred_at DATETIME(3) NOT NULL,
    PRIMARY KEY (id),
    KEY idx_audit_trace (trace_id),
    KEY idx_audit_operator_time (operator_user_id, occurred_at),
    KEY idx_audit_target (target_type, target_id),
    KEY idx_audit_order (order_id),
    KEY idx_audit_module_time (operation_module, occurred_at),
    CONSTRAINT chk_audit_result CHECK (result IN ('SUCCESS', 'FAILED'))
);
